name: Deploy AppPyToActions

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # 1. Fazer checkout do repositório
    - name: Checkout repository
      uses: actions/checkout@v3

    # 2. Configurar chave SSH
    - name: Setup SSH Key
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SERVER_PRIVATE_KEY }}

    # 3. Adicionar o servidor remoto ao arquivo known_hosts
    - name: Add server to known_hosts
      run: ssh-keyscan -H 201.23.3.86 >> ~/.ssh/known_hosts

    # 4. Conectar ao servidor e realizar o deploy
    - name: Deploy to Server
      run: |
        ssh seu-usuario@201.23.3.86 << 'EOF'
        cd /caminho/do/projeto            # Caminho do código no servidor
        git pull origin main              # Atualizar o código
        docker build -t app_py_to_actions .  # Construir a imagem Docker
        docker stop app_py_to_actions || true # Parar container antigo
        docker rm app_py_to_actions || true   # Remover container antigo
        docker run -d -p 8106:8106 --name app_py_to_actions app_py_to_actions # Subir novo container
        EOF
